### ISSUE TITLE
Finer controll on form submit

### ISSUE THREAD

**Issue by kamenjan** [globalpayments/globalpayments-js#31]
I'm working on implementing GlobalPayments in react based application, but I need more control over the form submit process and thus `action` & `method` form attributes are not enough - I need a specific data structure for the back end consumption.

Is there a way I can grab all the form fields after I get the temporary token and before `form.submit()` is called?

In normal form this would be a no-brainer, but these iFrames have been leading me down a rabbit hole for a better part of the day :(

Thank you for your selfless (sorry for the previous typo) and hard work on this open source package. 

Cheers!

**Comment by slogsdon** [comment]
@kamenjan Thanks for reaching out. This can be done within your `token-success` which will fire after the submit button has been clicked and a temporary token has been obtained, but the library doesn't control your payment form. Your integration code has the ability to control the final form submission, allowing you to follow any requirements from your client-side and server-side code.

```js
cardForm.on("token-success", (resp) => {
  // example using a standard input to hold the token during form submit
  // add payment token to form as a hidden input
  const token = document.createElement("input");
  token.type = "hidden";
  token.name = "payment-reference";
  token.value = resp.paymentReference;

  // compile data structure for form data
  // submit data to the integration's backend for processing
});
```

**Comment by kamenjan** [comment]
Oh, now I see - the data is sent back inside the response along with temporary token.

You saved me so much time, thank you very much!
