### ISSUE TITLE
High amount of Challenge Failures - How to Debug?

### ISSUE THREAD

**Issue by philipbelcher** [globalpayments/globalpayments-js#50]
Hello

We have a successful 3DS2 implementation using the PHP SDK and this library.

We followed the guide here: https://developer.globalpay.com/ecommerce/3d-secure-version2/browser-authentication#step-by-step-guide-for-javascript-library---sdk-

I can see that we do have successful 3DS2 Challenge payments, therefore it is set up correctly.

Yet we are seeing a large amount of Challenge Failures - with the user trying multiple times, suggesting they are not being presented with a Challenge window.

Here's a summary of where the issue is happening.

```javascript
try {
   authenticationData = await initiateAuthentication('/ThreeDSecure2/InitiateAuthentication', {
      data
   });

   if (authenticationData.result == "AUTHORIZATION_SUCCESS") {
      ...
   }

   else if (authenticationData.result == "AUTHORIZATION_FAILURE") {
      ...
   }

   else if (authenticationData.result == "AUTHENTICATION_FAILURE") {
      ...
   }

   // challenge success
   else if (authenticationData.challenge.response.data.transStatus == "Y") {
      ...
   }

   // challenge failure
   else {
      This is where we're ending up on these Challenge Failures
      ...
   }
}

catch (e) {

}
```
We're not seeing any errors thrown in the backend InitiateAuthentication endpoint.
In the final `else` above I am logging the contents of `authenticationData.challenge` for debugging purposes and it has the following inside it:
`requestUrl: 'a url to rsa3dauth.co.uk', encodedChallengeRequest: 'the encoded challenge request'` so as you can see, no challenge response.

The ChallengeWindow is configured as follows:
```javascript
challengeWindow: {
  windowSize: ChallengeWindowSize.FullScreen,
  displayMode: 'lightbox',
}
```

Has anyone seen this before or know how best to debug this?
Thanks

**Comment by rxp-developers** [comment]
Hello,

There was an issue with the ACS simulator and it's fixed now. Can you try
again please?

Best regards,
      Cristina.

On Tue, Jun 29, 2021 at 1:03 PM 'philipbelcher' via DL_Developers <
***@***.***> wrote:

> Hello
>
> We have a successful 3DS2 implementation using the PHP SDK and this
> library.
>
> We followed the guide here:
> https://developer.globalpay.com/ecommerce/3d-secure-version2/browser-authentication#step-by-step-guide-for-javascript-library---sdk-
>
> I can see that we do have successful 3DS2 Challenge payments, therefore it
> is set up correctly.
>
> Yet we are seeing a large amount of Challenge Failures - with the user
> trying multiple times, suggesting they are not being presented with a
> Challenge window.
>
> Here's a summary of where the issue is happening.
>
> try {
>    authenticationData = await initiateAuthentication('/ThreeDSecure2/InitiateAuthentication', {
>       data
>    });
>
>    if (authenticationData.result == "AUTHORIZATION_SUCCESS") {
>       ...
>    }
>
>    else if (authenticationData.result == "AUTHORIZATION_FAILURE") {
>       ...
>    }
>
>    else if (authenticationData.result == "AUTHENTICATION_FAILURE") {
>       ...
>    }
>
>    // challenge success
>    else if (authenticationData.challenge.response.data.transStatus == "Y") {
>       ...
>    }
>
>    // challenge failure
>    else {
>       This is where we're ending up on these Challenge Failures
>       ...
>    }
> }
>
> catch (e) {
>
> }
>
> We're not seeing any errors thrown in the backend InitiateAuthentication
> endpoint.
> In the final else above I am logging the contents of
> authenticationData.challenge for debugging purposes and it has the
> following inside it:
> requestUrl: 'a url to rsa3dauth.co.uk', encodedChallengeRequest: 'the
> encoded challenge request' so as you can see, no challenge response.
>
> The ChallengeWindow is configured as follows:
>
> challengeWindow: {
>   windowSize: ChallengeWindowSize.FullScreen,
>   displayMode: 'lightbox',}
>
> Has anyone seen this before or know how best to debug this?
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_globalpayments_globalpayments-2Djs_issues_50&d=DwMCaQ&c=zQ6tLaF7dShu6emFdFLQLQ&r=QDDMxukUX4zqjTxKNXuNmzSFpuFZFz9Hs0l2FXcTpQA&m=_F7l68lgtptogs7zLhfyrYQ4NaTbmjXpyo-cSc4OLKE&s=ICuhMnl5IuvNKaMeTsl7_uf4xYvMbNqV7Z9JrVpQHiE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG3Z63P334DENKR6FVEX3G3TVGK7HANCNFSM47PYKM3Q&d=DwMCaQ&c=zQ6tLaF7dShu6emFdFLQLQ&r=QDDMxukUX4zqjTxKNXuNmzSFpuFZFz9Hs0l2FXcTpQA&m=_F7l68lgtptogs7zLhfyrYQ4NaTbmjXpyo-cSc4OLKE&s=UOgQQoRNjWh61rejpdD0ti-Z1Q_ELQdCFy2d0yaxhho&e=>
> .
>

-- 
NOTICE: This email message is for the sole use of the addressee(s) named 
above and may contain confidential and privileged information. Any 
unauthorized review, use, disclosure or distribution of this message or any 
attachments is expressly prohibited. If you are not the intended recipient, 
please contact the sender by reply email and destroy all copies and backups 
of the original message.

**Comment by philipbelcher** [comment]
Hello. This is for the Live gateway not the test gateway!

**Comment by renaldas** [comment]
@philipbelcher  did you sorted this issue, we are getting exact same issues!

**Comment by philipbelcher** [comment]
> @philipbelcher did you sorted this issue, we are getting exact same issues!

Afraid we switched to using Stripe - and have had a lot better sleep since then!

**Comment by joanamal1** [comment]
Please unsubscribe my email ***@***.***
