### ISSUE TITLE
Does enableAutocomplete work?

### ISSUE THREAD

**Issue by ajselvig** [globalpayments/globalpayments-js#51]
We have a Heartland integration that works fine except that I can't get browser autocomplete to work in the card number field.  I'm configuring GlobalPayments with:

```
	GlobalPayments.configure(
		publicApiKey: '....'
		enableAutocomplete: true
	)
```

then constructing the form with `GlobalPayments.ui.form`. 

We're current using globalpayments.js from here: https://api2.heartlandportico.com/SecureSubmit.v1/token/gp-1.3.0/globalpayments.js

No browser autocomplete happens when clicking/typing into the card number field. Is there something I'm missing on how to get this feature working?

Thanks!

**Comment by slogsdon** [comment]
@ajselvig v1.3.0 doesn't have the autocomplete feature as this was deployed after v1.3.0. You should be able to update your URL for globalpayment.js to `https://js.globalpay.com/v1/globalpayments.js` and see this work as expected.

**Comment by ajselvig** [comment]
Thanks, @slogsdon, that worked!
