### ISSUE TITLE
3ds2 initiate authentication does not display challenge popup to the end user

### ISSUE THREAD

**Issue by aregier** [globalpayments/globalpayments-js#64]
Re-logging from deprecated repository: https://github.com/globalpayments/globalpayments-3ds-js/issues/29:

When an initiate authentication response (IInitiateAuthenticationResponseData) is received with the following data, the user is not prompted for a challenge response and the 3ds2 process fails, which blocks payments from moving forward:

challenge_mandated: false
status: "CHALLENGE_REQUIRED"

thanks,
Andrew

**Comment by aregier** [comment]
browser console log: https://docs.google.com/document/d/1KHktoXKrKBBHIwESoa2xNJpyqakQvL2o_l2JUkaTIAo/edit

**Comment by aregier** [comment]
This was an issue on our side; We needed a very similar fix to this one:

https://github.com/globalpayments/globalpayments-js/blob/master/packages/globalpayments-3ds/src/index.ts#L165

**Comment by slogsdon** [comment]
Thanks for circling back, @aregier.
